[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = [
    "invalid-name",
    "fixme",
    "too-many-instance-attributes",
    "too-many-arguments",
    "too-few-public-methods",
    "duplicate-code"
]
